# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

# Site Settings
title: "Guzel Ishmaeva"
name: "Guzel Ishmaeva"
description: "Ph.D. Candidate in Economics"
url: "https://guzelishmaeva.github.io"
baseurl: ""

# Navigation Menu
nav:
  - title: "home"
    url: /
  - title: "bio"
    url: /bio/
  - title: "research"
    url: /research/
  - title: "links"
    url: /links/
  - title: "email"
    url: "mailto:gvi2002@nyu.edu"

# Author Profile
author:
  name: "Guzel Ishmaeva"
  avatar: "/assets/images/profile.jpg"
  bio: "Ph.D. Candidate in Economics | Research in [Your Research Focus]"
  location: "New York, USA"
  email: "gvi2002@nyu.edu"
