# Theme Settings
minimal_mistakes_skin    : "air" # Choose a clean skin style

# Site Settings
locale                   : "en-US"
title                    : "Guzel Ishmaeva"
title_separator          : "-"
subtitle                 : "Ph.D. Candidate in Economics"
name                     : "Guzel Ishmaeva"
description              : "Ph.D. Candidate in Economics | Research in [Your Research Focus]"
url                      : "https://guzelishmaeva.github.io"
baseurl                  : ""
repository               : "guzelishmaeva/guzelishmaeva.github.io"
logo                     : "/assets/images/profile.jpg" # Update this with your photo path
masthead_title           : " " # Removes default site title from the masthead

# Navigation Menu
nav:
  - title: "home"
    url: /
  - title: "bio"
    url: /bio/
  - title: "research"
    url: /research/
  - title: "links"
    url: /links/
  - title: "email"
    url: "mailto:gvi2002@nyu.edu"

# Social Links (Modify based on your profiles)
social:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:gvi2002@nyu.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guzelishmaeva"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/your-profile"

# Site Author (Your details)
author:
  name: "Guzel Ishmaeva"
  avatar: "/assets/images/profile.jpg" # Make sure to upload your image here
  bio: "Ph.D. Candidate in Economics | Research in [Your Research Focus]"
  location: "New York, USA"
  email: "gvi2002@nyu.edu"

# Enable Author Profile
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar: right # Moves photo to the right
      toc: false

# GitHub Pages Deployment
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
